@OroIdentityServer = https://localhost:7280

### Endpoints de UserQueries
GET  https://localhost:7280/getuserinfo
Content-Type: application/json

###

GET  https://localhost:7280/users
Content-Type: application/json

###

GET  https://localhost:7280/getuserbyemail/{email}
Content-Type: application/json

###

GET  https://localhost:7280/getuserbyid/{id:guid}
Content-Type: application/json

###

### Endpoints de UserCommands
POST  https://localhost:7280/create
Content-Type: application/json

{
    "name": "John",
    "middleName": "Doe",
    "lastName": "Smith",
    "userName": "johnsmith",
    "email": "john.smith@example.com",
    "password": "password123",
    "identification": "123456789",
    "identificationTypeId": "{{$guid}}"
}

###

PATCH  https://localhost:7280/update
Content-Type: application/json

{
    "name": "Updated Name",
    "middleName": "Updated Middle",
    "lastName": "Updated Last",
    "userName": "updatedusername",
    "email": "updated.email@example.com",
    "password": "newpassword123",
    "identification": "987654321",
    "identificationTypeId": "{{$guid}}"
}

###

DELETE  https://localhost:7280/delete/{id:guid}
Content-Type: application/json

###

### Endpoints de RoleQueries
GET  {{OroIdentityServer}}/roles/get/{id:guid}
Content-Type: application/json

###

GET  {{OroIdentityServer}}/roles/getall
Content-Type: application/json

###

### Endpoints de RoleCommands
POST  {{OroIdentityServer}}/roles/create
Content-Type: application/json

{
    "name": "Admin",
    "description": "Administrator role"
}

###

### Endpoints de RoleClaims
GET  {{OroIdentityServer}}/roleclaims/get/{id:guid}
Content-Type: application/json

###

GET  {{OroIdentityServer}}/roleclaims/getbyrole/{roleId:guid}
Content-Type: application/json

###

POST  {{OroIdentityServer}}/roleclaims/associate
Content-Type: application/json

{
    "roleId": "{{$guid}}",
    "claimType": "Permission",
    "claimValue": "Read"
}

###

PUT  {{OroIdentityServer}}/roleclaims/update
Content-Type: application/json

{
    "id": "{{$guid}}",
    "claimType": "Permission",
    "claimValue": "Write"
}

###

DELETE  {{OroIdentityServer}}/roleclaims/delete/{id:guid}
Content-Type: application/json

###

### Endpoints de IdentificationTypeCommands
POST  {{OroIdentityServer}}/identificationtypes/create
Content-Type: application/json

{
    "name": "Passport"
}

###

PATCH  {{OroIdentityServer}}/identificationtypes/update
Content-Type: application/json

{
    "id": "{{$guid}}",
    "name": "Driver License"
}

###

DELETE  {{OroIdentityServer}}/identificationtypes/delete/{id:guid}
Content-Type: application/json

###

### Endpoints de IdentificationTypeQueries
GET  {{OroIdentityServer}}/identificationtypes/getall
Content-Type: application/json

###

### Endpoints de ScopeCommands
POST  {{OroIdentityServer}}/scopes/create
Content-Type: application/json

{
    "name": "api.read",
    "description": "Read access to API"
}

###

PUT  {{OroIdentityServer}}/scopes/update
Content-Type: application/json

{
    "name": "api.write",
    "description": "Write access to API"
}

###

DELETE  {{OroIdentityServer}}/scopes/delete/{name}
Content-Type: application/json

###

### Endpoints de ScopeQueries
GET  {{OroIdentityServer}}/scopes
Content-Type: application/json

###

### Endpoints de ApplicationQueries
GET  {{OroIdentityServer}}/applications
Content-Type: application/json

###

GET  {{OroIdentityServer}}/applications/{clientId}
Content-Type: application/json

###

### Endpoints de ApplicationCommands
POST  {{OroIdentityServer}}/applications/create
Content-Type: application/json

{
    "descriptor": {
        "clientId": "client-id",
        "clientSecret": "client-secret",
        "permissions": ["permission1", "permission2"]
    }
}

###

PUT  {{OroIdentityServer}}/applications/update
Content-Type: application/json

{
    "descriptor": {
        "clientId": "updated-client-id",
        "clientSecret": "updated-client-secret",
        "permissions": ["updated-permission1", "updated-permission2"]
    }
}

###

DELETE  {{OroIdentityServer}}/applications/delete/{clientId}
Content-Type: application/json

###

### Endpoints de OpenIddict
# Authorize Endpoint
GET  {{OroIdentityServer}}/connect/authorize
Content-Type: application/x-www-form-urlencoded
?client_id=OroIdentityServer.Web
&redirect_uri=https://your-redirect-uri
&response_type=code
&scope=openid profile email
&state=your_state_value
###
# Token Endpoint
POST  {{OroIdentityServer}}/connect/token
Content-Type: application/x-www-form-urlencoded
grant_type=authorization_code
&code=authorization_code_received
&redirect_uri=https://your-redirect-uri
&client_id=your_client_id
&client_secret=your_client_secret
###
# UserInfo Endpoint
GET  {{OroIdentityServer}}/connect/userinfo
Content-Type: application/json
Authorization: Bearer <your_actual_access_token>
###
# Revocation Endpoint
POST  {{OroIdentityServer}}/connect/revocation
Content-Type: application/x-www-form-urlencoded
token=token_to_revoke
&token_type_hint=access_token
###
# Introspection Endpoint
POST  {{OroIdentityServer}}/connect/introspect
Content-Type: application/x-www-form-urlencoded
token=token_to_introspect
&token_type_hint=access_token

### Endpoints de Consentimientos
GET  {{OroIdentityServer}}/consents/getbyuser/{userId:guid}
Content-Type: application/json
###
DELETE  {{OroIdentityServer}}/consents/revoke/{consentId:guid}
Content-Type: application/json
###

