@OroIdentityServer.Api_HostAddress = https://localhost:7280

POST {{OroIdentityServer.Api_HostAddress}}/api/users
Content-Type: application/json 

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com"
}

###