@OroIdentityServer = https://localhost:7280

### Endpoints de UserQueries
GET  {{OroIdentityServer}}/getuserinfo/{id:guid}
Content-Type: application/json

###

### Endpoints de UserCommands
POST  {{OroIdentityServer}}/create
Content-Type: application/json

{
    "name": "John Doe",
    "middleName": "Middle",
    "lastName": "Doe",
    "userName": "johndoe",
    "email": "john.doe@example.com",
    "password": "password123",
    "identification": "123456789",
    "identificationTypeId": "{{$guid}}"
}

###

PATCH  {{OroIdentityServer}}/update
Content-Type: application/json

{
    "name": "Updated Name",
    "middleName": "Updated Middle",
    "lastName": "Updated Last",
    "userName": "updatedusername",
    "email": "updated.email@example.com",
    "password": "newpassword123",
    "identification": "987654321",
    "identificationTypeId": "{{$guid}}"
}

###

DELETE  {{OroIdentityServer}}/delete/{{$guid}}
Content-Type: application/json

###